### ISSUE TITLE
Doesn't work with Terminator (Ubuntu)

### ISSUE THREAD

**Issue by sudodaksh** [sindresorhus/terminal-link#1]
While it does with the default gnome terminal, it doesn't work with Terminator.

![image](https://user-images.githubusercontent.com/23355449/44661797-6cc48680-aa29-11e8-8eb8-bba572a5921c.png)

**Comment by sindresorhus** [comment]
From the readme:

> [Supported terminals.](https://gist.github.com/egmontkob/eb114294efbcd5adb1944c9f3cb5feda)

> For unsupported terminals, the link will be printed in parens after the text: My website (https://sindresorhus.com).

Not all terminals support links. I can't do anything about that. Open an issue on the terminal issue tracker.

**Comment by sudodaksh** [comment]
Ahh, my bad. I didn't read that. Thanks tho.
