### ISSUE TITLE
VSCode links include the terminating paren ")"

### ISSUE THREAD

**Issue by kyeotic** [sindresorhus/terminal-link#11]
![image](https://user-images.githubusercontent.com/1187432/61674111-49d93b80-aca7-11e9-85ee-851025bf17cc.png)

**Comment by sindresorhus** [comment]
https://github.com/sindresorhus/terminal-link/issues/8#issuecomment-489718912

**Comment by kyeotic** [comment]
If you are going to have a fallback behavior for unsupprted terminals you
might as well take the closing paren off so that it works.

**Comment by kyeotic** [comment]
Or just add some white space before around the parens
