### ISSUE TITLE
3.0 doesn't support cjs

### ISSUE THREAD

**Issue by runspired** [sindresorhus/terminal-link#17]
Providing a cjs build would be nice for those of use not able to use esm. In my case other tooling (qunit) is incompatible even though my lowest supported node version (12.x) is compatible with this.

**Comment by sindresorhus** [comment]
I don't intend to provide CommonJS fallback.

**Comment by runspired** [comment]
Shouldn't you change the support matrix to not include node 12 then? CJS cannot import this lib synchronously at all in 12 and cannot import it async unless using experimental feature flags.

**Comment by ReeganExE** [comment]
> Providing a cjs build would be nice for those of use not able to use esm. In my case other tooling (qunit) is incompatible even though my lowest supported node version (12.x) is compatible with this.

Does anyone fix it on a fork?

#### Update: I give up! Just copy the source from ansi-escapes make the life easier.
```ts
function termilink(text: string, url: string): string {
  const OSC = '\u001B]';
  const BEL = '\u0007';
  const SEP = ';';

  return [OSC, '8', SEP, SEP, url, BEL, text, OSC, '8', SEP, SEP, BEL].join('');
}

```

https://github.com/sindresorhus/ansi-escapes/blob/2b3b59c56ff77a2afdee946bff96f1779d10d775/index.js#L92-L107
