### ISSUE TITLE
I have error with  dependencies "supports-hyperlinks"

### ISSUE THREAD

**Issue by m7yue** [sindresorhus/terminal-link#19]
why `terminal-link` is **ESM**, but `supports-hyperlinks` is **commonjs** ?
when i use terminal-link with `ts-node  xxx.ts`, i get an error:
```shell
Error [ERR_REQUIRE_ESM]: Must use import to load ES Module: xxxxx/node_modules/terminal-link/index.js
```

**Comment by sindresorhus** [comment]
> why terminal-link is ESM, but supports-hyperlinks is commonjs ?

That is unrelated to your problem.

**Comment by sindresorhus** [comment]
https://gist.github.com/sindresorhus/a39789f98801d908bbc7ff3ecc99d99c

You need to make your project ESM and also use TypeScript 4.7.
